In [2]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

Question 1

In [3]:
print(type(list_)) # Printing type of list_
print(type(array_list)) # Printing array_list

<class 'list'>
<class 'numpy.ndarray'>


Question 2

In [9]:
print("Data type of each element of list_")
for i in range(len(list_)): # Iterating through every element of list_
    print(type(i))   # Printing type of each element

print("Data type of each element of array_list")
for i in range(len(array_list)): # Iterating through every element of array_list
    print(type(i)) # Printing type of each element 

Data type of each element of list_
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
Data type of each element of array_list
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


Question 3

In [13]:
array_list = np.array(object = list_, dtype = int)

No, there will no difference in datatype of elements present in both variables list_ and array_list

In [15]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

print(num_array)

[[1 2 3]
 [4 5 6]]


Question 4

(i) shape

In [17]:
num_array.shape # Finding shape of num_array

(2, 3)

(ii) size

In [24]:
num_array.size # Finding size of num_array

6

Question 5

In [26]:
arr = np.random.randint(0,1,(3,3)) # Creating array of zeros only
print(arr) # printing array

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Question 6

In [27]:
d_matirix = np.diag([1,1,1,1,1,]) # Creating 5x5 identity matrix 
print(d_matirix) # Printing identity matrix

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
